<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<?php /** @var \Sapient\Worldpay\Block\Addnewcard $block */ ?>

<?php $storeCode = $block->getStoreCode(); ?>
<form class="form form-edit-account" name="addnewcardform" data-mage-init='{"validation":{}}'
      method="post" id="form_add_card" autocomplete="off">
    <fieldset class="fieldset info">
        <?= /* @noEscape */ $block->getBlockHtml('formkey') ?>
        <legend class="legend">
            <span><?= /* @noEscape */ $block->getAccountLabelbyCode('AC8')
                    ?: $escaper->escapeHtml(__('Card Information')) ?>
            </span>
        </legend><br>

        <div class="field required">
            <label class="label" for="cc_type" id="cc_type_label">
                <span><?= /* @noEscape */ $block->getCheckoutSpecificLabel('CO1')
                        ?: $escaper->escapeHtml(__('Credit Card Type')); ?>
                </span>
            </label>
            <div class="control">
            <?php $cctypes = $block->getCCtypes(); ?>
                <select id="cc_type"
                        name="paymentType"
                        class="required-entry validate-cc-type-select control-select-new-card paymentType"
                        aria-labelledby="cc_type_label"
                        aria-required="true"
                        autocomplete="off">
                    <option value="" selected="selected">
                        <?= /* @noEscape */ $block->getAccountLabelbyCode('IAVAC2')
                            ?: $escaper->escapeHtml(__('Card type')); ?>
                    </option>
                    <?php
                    $options = '';
                    foreach ($cctypes as $k => $v) {
                        // Exclude ELO card type from the list until further notice
                        if ($k == 'ELO-SSL') {
                            continue;
                        }
                        $options .= '<option value="' . $k . '">' . $v . '</option>';
                    }
                    ?>
                    <?= /* @noEscape */  $options; ?>
                </select>
            </div>
        </div>

        <div class="field required">
            <label class="label" for="card_number">
                <span>
                    <?= /* @noEscape */ $block->getAccountLabelbyCode('AC3')
                        ?: $escaper->escapeHtml(__('Card Number')) ?>
                </span>
            </label>
            <div class="control">
                <input type="number" name="cardNumber" required="required" id="card_number"
                    title="<?= /* @noEscape */ $block->getCheckoutLabelbyCode('CO3')
                        ?: $escaper->escapeHtml(__('Card Number')) ?>"
                    class="input-text required validate-cc-number worldpay-cardnumber-valid cardNumber" />
            </div>
            <div id="card_number_msg" class="wp-error"></div>
        </div>

        <div class="field required">
            <label class="label" for="card_holder_name">
                <span>
                    <?= /* @noEscape */ $block->getCheckoutLabelbyCode('CO4')
                        ?: $escaper->escapeHtml(__('Card Holder Name')) ?>
                </span>
            </label>
            <div class="control">
                <input type="text" name="cardHolderName" required="required" id="card_holder_name"
                       title="<?= /* @noEscape */ $block->getCheckoutLabelbyCode('CO4')
                            ?: $escaper->escapeHtml(__('Card Holder Name'))?>"
                       class="input-text required cardholder_name worldpay-cardholdername-length cardHolderName" />
            </div>
        </div>

        <div class="field required">
            <label class="label" for="expiry_month" id="expiry_month_year">
                <span><?= /* @noEscape */ $block->getAccountLabelbyCode('AC10')
                    ?: $escaper->escapeHtml(__('Expiry Month/Year'))?>
                </span>
            </label>
            <div class="fields group group-2">
                <div class="field no-label month">
                    <div class="control">
                        <select id="expiry_month" name="expiryMonth" aria-labelledby="expiry_month_year"
                                class="month required validate-cc-exp required-entry worldpay-month-included
                                worldpay-month-length worldpay-month-range expiryMonth">
                            <?php foreach ($block->getMonths() as $k => $v): ?>
                                <option value="<?= /* @noEscape */ $escaper->escapeHtml($k) ?>">
                                <?= /* @noEscape */ $escaper->escapeHtml($v) ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="field no-label year">
                    <div class="control">
                        <select id="expiry_year" name="expiryYear" aria-labelledby="expiry_month_year"
                                class="year required required-entry
                                worldpay-year-included
                                worldpay-year-length
                                worldpay-year-range expiryYear">
                            <?php foreach ($block->getExpiryYears() as $k => $v): ?>
                                <option value="<?= /* @noEscape */$escaper->escapeHtml($k) ?>">
                                <?= /* @noEscape */ $escaper->escapeHtml($v) ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            </div>
        </div>

        <?php if ($block->requireCvcEnabled()): ?>
        <div class="field required _required cvv">
            <label for="cvv" class="label">
                <span><?= /* @noEscape */ $block->getCheckoutSpecificLabel('CO5')
                        ?: $escaper->escapeHtml(__('CVV')); ?>
                </span>
            </label>
            <div class="control">
                <input type="password" autocomplete="off" maxlength="4" length="4" id="cvv"
                       class="input-text required cvv saved-cvv-number required-entry
                       validate-card-cvv validate-length maximum-length-4 cvc"
                       name="cvc"
                       value=""/>
            </div>
            <div id="cvv_msg" class="wp-error"></div>
        </div>
        <?php endif; ?>

        <!-- Disclaimer -->
        <div>
            <span class="label">
                <?php if ($block->getStoredCredentialsEnabledValue() && $block->getDisclaimerMessageEnable()): ?>
                    <span>(<a href="javascript:void(0)"
                            role="button"
                            id="important-disclaimer"><?=
                                /* @noEscape */ $escaper->escapeHtml(
                                    $block->getCheckoutLabels('CO9') ?: __('Important Disclaimer!')
                                )
                        ?></a>)</span>
                <?php endif; ?>
            </span>
            <div id="dialog" title="<?= /* @noEscape */ $escaper->escapeHtml($block->getCheckoutLabels('CO9')
                    ?: __('Important Disclaimer!')
                )?>"
            >
                <form id="disclaimer" name="disclaimer">
                    <div><?= /* @noEscape */ $block->getDisclaimerText(); ?></div>
                </form>
            </div>
            <div class="mage-error" generated="true" id="disclaimer-error"></div>
        </div>

        <div class="field billing-address">
            <span class="label" for="billing-address">
                <span><?= /* @noEscape */ $escaper->escapeHtml(
                        $block->getAccountLabelbyCode('IAVAC3') ?: __('Default Billing Address')
                    ) ?>
                </span>
            </span>
            <div class="control">
                <address><?= $block->getPrimaryBillingAddressHtml() ?></address>
            </div>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden"
                       name="cseEnabled"
                       id="worldpay_cse_enabled"
                       value=""/>
                <input type="hidden"
                       name="dfReferenceId"
                       id="dfReferenceId"
                       value=""/>
                <button type="submit" class="action save primary"
                        onclick="javascript:onConfirmBtn(); return false;"
                        id ="save_newcard"
                        title="
                            <?= /* @noEscape */ $block->getAccountLabelbyCode('AC39')
                                ?: $escaper->escapeHtml(__('Save'))?>" >
                    <span>
                        <?= /* @noEscape */ $block->getAccountLabelbyCode('AC39')
                            ?: $escaper->escapeHtml(__('Save')) ?>
                    </span>
                </button>
            </div>
        </div>
    </fieldset>
</form>
<?php
$baseurl = /* @noEscape */ $block->getBaseUrl();
$exception = /* @noEscape */ $block->getCreditCardSpecificexception('CTYP01');
$isCVCRequired = /* @noEscape */ $escaper->escapeHtml($block->requireCvcEnabled());
$mandatoryMessage = /* @noEscape */ $escaper->escapeHtml($block->getDisclaimerMessageMandatory());
$disclaimerMessageEnabled = /* @noEscape */ $escaper->escapeHtml($block->getDisclaimerMessageEnable());
$storedCredentials = /* @noEscape */ $escaper->escapeHtml($block->getStoredCredentialsEnabledValue());

$textCVVMsg = __("Please enter a valid number in this field");
$textCVVMsg4 = __("Please, Enter 4 digit valid Card Verification Number");
$textCVVMsg3 = __("Please, Enter 3 digit valid Card Verification Number");
$textTypeErrorMsg = __('Card number entered does not match with card type selected');
$textRequiredField = __('This field is required');
$textVerifyDisclaimer = __('Please, Verify the disclaimer! before saving');

$scriptString = <<<script
    require(['jquery',
        'mage/url',
        'prototype'
    ], function ($, urlBuilder) {
        var baseUrl = '$baseurl';
        var typeCamMsg = '$exception';
        var jwtUrl = baseUrl + 'worldpay/hostedpaymentpage/jwt';

        function createJwt(cardNumber) {
            var bin = cardNumber;
            var encryptedBin = btoa(bin);
            var iframe = document.createElement('iframe');
            iframe.src = jwtUrl + '?instrument=' + encryptedBin;
            iframe.name = "jwt_frm";
            iframe.id = "jwt_frm";
            iframe.style.display = "none";
            document.body.appendChild(iframe);
        }

        function validateCVV() {
            var cvv = document.getElementById('cvv').value;
            var numbers = /^[0-9]+$/;
            if(cvv.match(numbers)){
                document.getElementById("cvv_msg")
                                .innerHTML = '';
                if (document.addnewcardform.paymentType.value == "AMEX-SSL") {
                    if (document.getElementById('cvv').value.length != 4) {
                        document.getElementById("cvv_msg")
                                .innerHTML = '$textCVVMsg4';
                        document.addnewcardform.cvc.focus();
                        return false;
                    } else {
                        return true;
                    }
                } else {
                    if (document.getElementById('cvv').value.length != 3) {
                        document.getElementById("cvv_msg")
                                .innerHTML = '$textCVVMsg3';
                        document.addnewcardform.cvc.focus();
                        return false;
                    } else {
                        return true;
                    }
                }
            }
            else {
                document.getElementById("cvv_msg")
                    .innerHTML = '$textCVVMsg';
                document.addnewcardform.cvc.focus();
                return false;
            }
        }

        function getCardType() {
            var cardType = document.addnewcardform.paymentType.value;
            var cardnumber = document.getElementById('card_number').value;

             var curVal = cardnumber.replace(/ /g, '').replace(/-/g, '');

            const regexMap = {
                'ELO-SSL': /^(401178|401179|431274|438935|451416|457393|457631|457632|504175|627780|636297|636368|655000|655001|651652|651653|651654|650485|650486|650487|650488|506699|5067[0-6][0-9]|50677[0-8]|509\d{3})\d{10}$/,
                'VISA-SSL': /^4[0-9]{0,20}$/,
                'ECMC-SSL': /^(?:5[1-5][0-9]{0,2}|222[1-9]|22[3-9][0-9]|2[3-6][0-9]{0,2}|27[01][0-9]|2720)[0-9]{0,12}$/,
                'AMEX-SSL': /^3$|^3[47][0-9]{0,13}$/,
                'DISCOVER-SSL': /^6[05]$|^601[1]?$|^65[0-9][0-9]?$|^6(?:011|5[0-9]{2})[0-9]{0,12}$/,
                'JCB-SSL': /^35(2[89]|[3-8][0-9])/,
                'DINERS-SSL': /^36/,
                'MAESTRO-SSL': /^(5018|5020|5038|6304|679|6759|676[1-3])/,
                'DANKORT-SSL': /^(5019|4571)/
            };

            if (cardType === 'CB-SSL' && (regexMap['ECMC-SSL'].test(curVal) || regexMap['VISA-SSL'].test(curVal))) {
                return 'CB-SSL';
            }
            if (cardType === 'CARTEBLEUE-SSL' && regexMap['ECMC-SSL'].test(curVal)) {
                return 'CARTEBLEUE-SSL';
            }
            for (const [type, regex] of Object.entries(regexMap)) {
                if (regex.test(curVal)) {
                    return type;
                }
            }

            return null;
        }

        function checkCardTypeValidity()
        {
            document.getElementById("card_number_msg")
                            .innerHTML = '';
            var cardType = document.addnewcardform.paymentType.value;
            var cardNumberType = getCardType();
            var typeErrorMsg = '$textTypeErrorMsg';
            var cardTypeErrorDisplay = typeCamMsg ? typeCamMsg : typeErrorMsg;
            if (cardType === cardNumberType) {
                return true;
            }else if ((cardType === 'CB-SSL' || cardType === 'CARTEBLEUE-SSL')
                    && cardNumberType === 'ECMC-SSL') {
                return true;
            }
            else {
                document.getElementById("card_number_msg")
                    .innerHTML = cardTypeErrorDisplay;
                return false;
            }
        }
        function checkEmptyValidation (){
            var valid = false;
            var paymentType = document.addnewcardform.paymentType.value;
            var cardNumber = document.addnewcardform.cardNumber.value;
            var cardHolderName = document.addnewcardform.cardHolderName.value;
            var expiryMonth = document.addnewcardform.expiryMonth.value;
            var expiryYear = document.addnewcardform.expiryYear.value;
            var cvc = document.addnewcardform.cvc.value;
            const errorHtml = [paymentType,cardNumber,cardHolderName,expiryMonth,expiryYear,cvc];

            jQuery.each(errorHtml, function(index, value){
                if(!value){
                    valid = false;
                    displayError(index);
                    return false;
                }else{
                    valid = true;
                    jQuery(".errmsg").remove();
                }
            });
            return valid;
        }

        function displayError(index){
            const errorHtml = [
                            'paymentType',
                            'cardNumber',
                            'cardHolderName',
                            'expiryMonth',
                            'expiryYear',
                            'cvc'
                        ];
            var value = errorHtml[index];
            jQuery('.'+value).after('<span class="errmsg wp-error">$textRequiredField</span>');
            jQuery('.'+value).focus();
        }

        function onConfirmBtn() {
            let valid = checkEmptyValidation();
            if(!valid){
                return false;
            }
            var isCvcRequired = Boolean($isCVCRequired);
            var isCvvValid = (isCvcRequired === true ? validateCVV() : true);
            var cvvValid = isCvvValid && checkCardTypeValidity();

            mandatoryMessage= parseInt("$mandatoryMessage");
            disclaimerMessageEnabled = parseInt("$disclaimerMessageEnabled");
            storedCredentials = parseInt("$storedCredentials");
            if (cvvValid && jQuery('#form_add_card').valid() && !(window.isDynamic3DS2Enabled)) {
                document.getElementById('save_newcard').disabled=true;
                if(mandatoryMessage && disclaimerMessageEnabled && window.disclaimerDialogue === null){
                        $('#disclaimer-error').css('display', 'block');
                            $('#disclaimer-error').html("$textVerifyDisclaimer");
                        return false;
                    }
                /*if((window.is3DsEnabled)) {
                createPayment3DS();
                }else {*/
                createPayment();
            //}
            } else if (cvvValid && jQuery('#form_add_card').valid() && window.isDynamic3DS2Enabled) {
                document.getElementById('save_newcard').disabled=true;

                if(mandatoryMessage && disclaimerMessageEnabled && window.disclaimerDialogue === null){
                    $('#disclaimer-error').css('display', 'block');
                    $('#disclaimer-error').html("$textVerifyDisclaimer");
                    return false;
                }

                var bin = jQuery('[name=cardNumber]').val();
                var binNew = bin.substring(0, 6);
                createJwt(binNew);
                window.sessionId = '';
                window.addEventListener("message", function (event) {
                    console.log("inside listener");
                    var data = JSON.parse(event.data);
                    var envUrl;
                    if (window.jwtEventUrl !== '') {
                        envUrl = window.jwtEventUrl;
                    }
                    if (event.origin === envUrl) {
                        var data = JSON.parse(event.data);
                        if (data !== undefined) {
                            // for cardinal
                            if(data.Payload){
                                if(data.Payload.ActionCode =="SUCCESS"){
                                    var sessionId = data.Payload.SessionId;
                                    if (sessionId) {
                                        dfReferenceId = sessionId;
                                    }
                                    window.sessionId = dfReferenceId;
                                    jQuery('[name=dfReferenceId]').val(dfReferenceId);
                                    createPayment3DS();
                                }
                            } else if(data.Status) {
                                var sessionId = data.SessionId;
                                if (sessionId) {
                                    dfReferenceId = sessionId;
                                }
                                window.sessionId = dfReferenceId;
                                jQuery('[name=dfReferenceId]').val(dfReferenceId);
                                createPayment3DS();
                            }
                        }
                    }
                }, false);
            }
            function createPayment() {
                var paymentDetails = {
                    "payment": {
                        "cardNumber": jQuery('[name=cardNumber]').val(),
                        "paymentType": jQuery('[name=paymentType]').val(),
                        "cardHolderName": jQuery('[name=cardHolderName]').val(),
                        "expiryMonth": jQuery('[name=expiryMonth]').val(),
                        "expiryYear": jQuery('[name=expiryYear]').val(),
                        "cvc": jQuery('[name=cvc]').val(),
                        "cseEnabled": jQuery('[name=cseEnabled]').val(),
                        "disclaimerFlag": disclaimerFlag,
                        'browser_screenheight': window.screen.height,
                        'browser_screenwidth': window.screen.width,
                        'browser_colordepth': window.screen.colorDepth
                    }
                };
                var jsonPaymentDetails = JSON.stringify(paymentDetails);
                $.ajax({
                    url: urlBuilder.build('worldpay/savedcard/addnewcardPost'),
                    data: jsonPaymentDetails,
                    type: 'post',
                    xhrFields: {
                        withCredentials: true
                    },
                    success: function (data, status, jqXHR) {
                        response = JSON.stringify(data);
                        var result = JSON.parse(response);
                        if (result.threeD) {
                            window.location.href = baseUrl + 'worldpay/savedcard/redirect';
                            return;
                        }
                        if (result.success) {
                            window.location.replace(urlBuilder.build('worldpay/savedcard'));
                            return;
                        } else {
                            window.location.replace(urlBuilder.build('worldpay/savedcard/addnewcard'));
                            return;
                        }
                    },
                    error: function (error) {
                        response = JSON.stringify(error)
                        window.location.replace(urlBuilder.build('worldpay/savedcard/addnewcard'));
                    },
                    /** Show loader before send */
                    beforeSend: function () {
                        $('body').trigger('processStart');
                    }
                }).always(function () {
                    $('body').trigger('processStop');
                });
            }
            function createPayment3DS() {
                var paymentDetails = {
                    "payment": {
                        "cardNumber": jQuery('[name=cardNumber]').val(),
                        "paymentType": jQuery('[name=paymentType]').val(),
                        "cardHolderName": jQuery('[name=cardHolderName]').val(),
                        "expiryMonth": jQuery('[name=expiryMonth]').val(),
                        "expiryYear": jQuery('[name=expiryYear]').val(),
                        "cvc": jQuery('[name=cvc]').val(),
                        "cseEnabled": jQuery('[name=cseEnabled]').val(),
                        "dfReferenceId": window.sessionId,
                        "disclaimerFlag": disclaimerFlag,
                        'browser_screenheight': window.screen.height,
                        'browser_screenwidth': window.screen.width,
                        'browser_colordepth': window.screen.colorDepth
                    }
                };
                var jsonPaymentDetails = JSON.stringify(paymentDetails);
                $.ajax({
                    url: urlBuilder.build('worldpay/savedcard/addnewcardPost'),
                    data: jsonPaymentDetails,
                    type: 'post',
                    success: function (data) {
                        response = JSON.stringify(data);
                        var result = JSON.parse(response);
                        console.log(result);
                        if((result.threeDError == true) || (result.success == false)) {
             window.location.replace(urlBuilder.build('worldpay/savedcard/addnewcard'));
            }else {
            console.log("entered success case to go to auth");
                        window.location.replace(urlBuilder.build('worldpay/threedsecure/auth'));
                    }
                    },
                    error: function (data) {
                        window.location.replace(urlBuilder.build('worldpay/savedcard/addnewcard'));
                    },
                    /** Show loader before send */
                    beforeSend: function () {
                        $('body').trigger('processStart');
                    }

                }).always(function () {
                    $('body').trigger('processStop');
                });
            }

        }
        window.onConfirmBtn = onConfirmBtn;
        $(document).ready(function (){
          window.disclaimerDialogue=null;
          disclaimerFlag=null;
        });
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php $scriptString = <<<script
    {
        ".page-main": {
            "disclaimerPopup": {
                "disclaimer": "a#important-disclaimer",
                "mandatoryMessage": "$mandatoryMessage",
                "disclaimerMessageEnabled": "$disclaimerMessageEnabled",
                "storedCredentials": "$storedCredentials"
            }
        }
    }
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', ['type' => 'text/x-magento-init'], $scriptString, false) ?>
