<?php

/**
 * @var \Sapient\Worldpay\Block\Jwt $block
 */
$params = $block->getRequest()->getParams();
$ccNumber = '';
if ($params) {
    $ccNumber = str_replace(' ', '+', $params['instrument']);
}
$ddcUrl = $block->getDdcUrl();
$decoder = $block->getDecoder();
?>

<form method="post" action="<?= /* @noEscape */ $ddcUrl;?>" id="collectionForm" name="collectionForm"> 
    <input type="hidden" name="Bin" id="first_bin" value="<?= /* @noEscape */ $decoder->decode($ccNumber); ?>" />
    <input type="hidden" name="JWT" id="first_jwt" value="<?= /* @noEscape */ $block->getJwtToken(); ?>" />
</form>

<script language="Javascript">    
    window.onload = function()
    {
      // Auto submit form on page load
      document.getElementById("collectionForm").submit();
    }

</script>
