
<?php  $_savecards=$block->getSavedCard(); ?>

<?= /* @noEscape */ $block->getChildHtml('info');?>
<?php if ($_savecards && count($_savecards)): ?>
    <div class="table-wrapper saved-cards">
        <table class="data table table-savedcard-items history" id="my-savecards-table">
            <caption class="table-caption"><?= /* @noEscape */__('Saved Cards') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= /* @noEscape */ __('Card Brand #') ?></th>
                       <th scope="col" class="col date"><?= /* @noEscape */ __('Card Number') ?></th>
                       <th scope="col" class="col shipping"><?= /* @noEscape */ __('Card Holder Name') ?></th>
                    <th scope="col" class="col total"><?= /* @noEscape */ __('Card Expiry Month') ?></th>
                    <th scope="col" class="col status"><?= /* @noEscape */ __('Card Expiry Year') ?></th>
                    <th scope="col" class="col actions">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_savecards as $_savecard): ?>
                
               
               
                    <tr>
                        <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Card Brand #')) ?>"
                            class="col id"><?= /* @noEscape */ $_savecard->getCardBrand() ?>
                        </td>
                           <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Card Number')) ?>"
                               class="col date"><?= /* @noEscape */ $_savecard->getCardNumber() ?>
                           </td>
                        <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Card Holder Name')) ?>"
                            class="col shipping"><?= /* @noEscape */ $_savecard->getCardholderName() ?>
                        </td>
                        <td data-th="<?= /* @noEscape */$block->escapeHtml(__('Card Expiry Month')) ?>"
                            class="col total"><?= /* @noEscape */ $_savecard->getCardExpiryMonth() ?>
                        </td>
                        <td data-th="<?= /* @noEscape */$block->escapeHtml(__('Card Expiry Year')) ?>"
                            class="col status"><?= /* @noEscape */ $_savecard->getCardExpiryYear() ?>
                        </td>
                        <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Actions')) ?>" class="col actions">
                           
                              <?php
                                if ($_savecard->getTokenCode() != '') {
                                    ?>
                            <a href="<?= /* @noEscape */ $block->getEditUrl($_savecard) ?>" class="action view">
                                <span><?= /* @noEscape */ __('Update') ?></span>
                            </a>
                                    <?php
                                }
                                ?>
                            
                        </td>
                        <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <a href="<?= /* @noEscape */ $block->getDeleteUrl($_savecard) ?>" class="action view">
                                <span><?= /* @noEscape */ __('Delete') ?></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php else: ?>
    <div class="message info empty">
        <span><?= /* @noEscape */ __('You have no Saved Card.'); ?></span>
    </div>
<?php endif ?>
