
<?php $carddeatils = $block->getTokenData() ?>
<form class="form form-edit-account"
    action="<?= /* @noEscape */ $block->getUrl("worldpay/savedcard/editPost") ?>"
    method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
    <fieldset class="fieldset info">
        <?= /* @noEscape */ $block->getBlockHtml('formkey')?>
        <legend class="legend">
            <span>
                <?= /* @noEscape */ $block->getAccountLabelbyCode('AC8') ?
                        $block->getAccountLabelbyCode('AC8') :
                        $block->escapeHtml(__('Card Information')) ?>
            </span></legend><br>

        <input type="hidden" name="token[id]" value="<?= /* @noEscape */ $carddeatils->getTokenCode() ?>" />

        <div class="field card Number">
            <label class="label" for="card number">
                <span>
                    <?= /* @noEscape */ $block->getAccountLabelbyCode('AC3') ?
                            $block->getAccountLabelbyCode('AC3') :
                            $block->escapeHtml(__('Card Number')) ?>
                </span>
            </label>
            <div class="control">
                <span><?= /* @noEscape */ $block->escapeHtml($carddeatils->getCardNumber()) ?></span>
            </div>
        </div>

        <div class="field card holder name">
            <label class="label" for="card holder name">
                <span>
                    <?= /* @noEscape */ $block->getCheckoutLabelbyCode('CO4') ?
                            $block->getCheckoutLabelbyCode('CO4') :
                            $block->escapeHtml(__('Card Holder Name')) ?>
                </span>
            </label>
            <div class="control">
                <input type="text" name="token[cardholder_name]" required='true' id="card-holder-name" 
                       title="<?= /* @noEscape */
                        $block->getCheckoutLabelbyCode('CO4') ?
                        $block->getCheckoutLabelbyCode('CO4') :
                        $block->escapeHtml(__('Card Holder Name')) ?>"
                value="<?= /* @noEscape */ $block->escapeHtml($carddeatils->getCardholderName()) ?>"
                class="input-text required cardholder_name worldpay-cardholdername-length">
            </div>
        </div>

        <div class="field card expiry month">
            <label class="label" for="card holder name">
                <span>
                    <?= /* @noEscape */
                    $block->getAccountLabelbyCode('AC10') ?
                            $block->getAccountLabelbyCode('AC10') :
                            $block->escapeHtml(__('Expiry Month/Year')) ?>
                </span>
            </label>
            <div class="fields group group-2">
                <div class="field no-label month">
                    <div class="control">
                        <select id="expiry_month" name="token[card_expiry_month]"
                        class="month required-entry worldpay-month-included worldpay-month-length worldpay-month-range">
                        <?php foreach ($block->getMonths() as $k => $v): ?>
                            <option value="<?= /* @noEscape */ $block->escapeHtml($k) ?>"
                                <?php if ($k == $carddeatils->getCardExpiryMonth()): ?>
                            selected<?php endif ?>>
                            <?= /* @noEscape */ $block->escapeHtml($v) ?></option>
                        <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="field no-label year">
                    <div class="control">
                        <select id="expiry_month" name="token[card_expiry_year]"
                              class="month required-entry
                              worldpay-month-included
                              worldpay-month-length
                              worldpay-month-range">
                        <?php foreach ($block->getExpiryYears() as $k => $v): ?>
                            <option value="<?= /* @noEscape */$block->escapeHtml($k) ?>"
                                <?php if ($k == $carddeatils->getCardExpiryYear()): ?>
                            selected<?php endif ?>>
                            <?= /* @noEscape */ $block->escapeHtml($v) ?></option>
                        <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action save primary"
                        title="<?= /* @noEscape */
                        $block->getAccountLabelbyCode('AC39') ?
                        $block->getAccountLabelbyCode('AC39') : $block->escapeHtml(__('Save')) ?>">
                    <span>
                        <?= /* @noEscape */
                        $block->getAccountLabelbyCode('AC39') ?
                        $block->getAccountLabelbyCode('AC39') : $block->escapeHtml(__('Save')) ?>
                    </span>
                </button>
            </div>
        </div>
    </fieldset>

</form>
