<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<script>
require([
     'Magento_Customer/js/customer-data'
 ], function (customerData) {
     var sections = ['cart'];
     customerData.reload(sections, true);
 });
</script>

<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()):?>
            <p>
             <?= /* @noEscape */ __(
                 'Your order number is: %1.',
                 sprintf(
                     '<a href="%s" class="order-number"><strong>%s</strong></a>',
                     $escaper->escapeHtml($block->getViewOrderUrl()),
                     $escaper->escapeHtml($block->getOrderId())
                 )
             )  ?>
            </p>
        <?php  else:?>
            <p>
            <?= /* @noEscape */ __(
                'Your order # is: <span>%1</span>.',
                $escaper->escapeHtml($block->getOrderId())
            ) ?>
            </p>
        <?php endif;?>
            <p><?= /* @noEscape */    __('We\'ll email you an order confirmation with details and tracking info.') ?>
            </p>
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= /* @noEscape */ $block->getContinueUrl() ?>">
                <span><?= /* @noEscape */ __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
