<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<?php /** @var \Sapient\Worldpay\Block\Recurring\Customer\Subscriptions\OrderInfo\AddressInfo $block */ ?>

<?php $address_options = $block->getAddressOptions() ?>
<div id="change_shipping_modal" style="display:none">
    <div class="shipping-modal-body-content mb-20">
        <p class="successmsg" data-bind="i18n: successmsg(), attr: {class: msgColor() }"></p>
        <label for="ship-address-dropdown"><?= $escaper->escapeHtml(__('Shipping Address')) ?>:</label>
        <select name="current-shipping-addresses" id="ship-address-dropdown"
            data-bind="event:{ change: fetchShippingMethodByAddress }" >
        <?php foreach ($address_options as $key => $option): ?>
                <option value="<?= $escaper->escapeHtml(__($option['value'])) ?>">
                <?= $escaper->escapeHtml(__($option['label'])); ?></option>
        <?php endforeach; ?>
        </select>
    </div>

    <div class="ship-via" data-bind="blockLoader: isLoadingShippingMethod">
        <!-- ko if: (availableShippingMethods().length)-->
        <div class="shipping-information-title">
            <span data-bind="i18n: 'Shipping Method:'"></span>
        </div>
         <!-- /ko -->
        <div class="shipping-information-content">
                <p class="ship-method-error" style="display:none; color:red"
                data-bind="i18n: 'Please select shipping method'"></p>
                <!-- ko if: (availableShippingMethods().length)-->
                    <!-- ko foreach: {data: availableShippingMethods(), as: 'item'} -->
                    <div class="shippingmethods-radio-wrapper">
                            <input type="radio"
                                data-bind="attr: {
                                    'value': item.identifier,
                                    id: 'recurring_ship_method' + item.identifier
                                }"
                                name="shipping_method_recurring" />
                            <label data-bind="attr: {
                                    for: 'recurring_ship_method' + item.identifier},
                                    i18n: item.label">
                            </label>
                    </div>
                    <!-- /ko -->
            <!--/ko-->
            <!-- ko if: (availableShippingMethods().length == 0)-->
            <div class="shippingmethods-radio-wrapper">
                <span data-bind="ii18n: 'Shipping method is not available'"></span>
            </div>
            <!-- /ko-->
        </div>
    </div>
</div>
