<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<?php /** @var \Magento\Sales\Block\Order\Info $block */ ?>

<?php $_order = $block->getCurrentSubscriptionOrder() ?>

<div class="block block-order-details-view" data-bind="scope: 'worldpay_subscription'">
    <div class="block-title">
        <strong><?= /* @noEscape */ $escaper->escapeHtml(__('Subscription Addresses')) ?></strong>
    </div>
    <div class="block-content">
     <div class="box box-order-billing-address">
            <strong class="box-title">
                <span><?= /* @noEscape */ $escaper->escapeHtml(__('Billing Address')) ?></span>
            </strong>
            <div class="box-content">
                <address>
                    <?= /* @noEscape */ $block->getFormattedAddress($_order->getBillingAddress()) ?>
                </address>
            </div>
        </div>
        <?php if (!$_order->getIsVirtual()): ?>
            <div class="box box-order-shipping-address">
                <strong class="box-title">
                    <span><?= /* @noEscape */ $escaper->escapeHtml(__('Shipping Address')) ?></span>
                </strong>
                <div class="box-content">
                    <address><?= $block->getFormattedAddress($_order->getShippingAddress()) ?></address>
                    <span>
                        <a href="#" data-bind="click: openShippingPopup" id="change-shipping-address">
                            <?= /* @noEscape */ $escaper->escapeHtml(__('Change Shipping Address')) ?>
                        </a>
                    </span>
                </div>
            </div>
        <?php endif; ?>
    </div>
    <?php if (!$_order->getIsVirtual()): ?>
    <div class="block-title">
        <strong><?= /* @noEscape */ $escaper->escapeHtml(__('Shipping Method')) ?></strong>
    </div>
    <div class="block-content mb-30">
        <?php if ($_order->getShippingDescription()): ?>
            <span><?= /* @noEscape */ $escaper->escapeHtml($_order->getShippingDescription()) ?></span>
        <?php else: ?>
            <?= /* @noEscape */ $escaper->escapeHtml(__('No shipping information available')) ?>
        <?php endif; ?>
    </div>
    <?php endif; ?>
    <div class="block-title">
        <strong><?= $escaper->escapeHtml(__('Payment Method')) ?></strong>
    </div>
    <div class="block-content payment-method">
        <?php $transactionData = $block->getTransactionData($_order); ?>
        <p><?= /* @noEscape */ $escaper->escapeHtml(__($transactionData->getCardNumber())) ?> -
            <?= /* @noEscape */ $escaper->escapeHtml(__($transactionData->getCardBrand())); ?> </p>
        <span>
            <a href="#" id="change-payment-method" data-bind="click: openPaymentPopup">
                <?= /* @noEscape */ $escaper->escapeHtml(__('Change Payment Method')) ?>
            </a>
        </span>
    </div>

<?= $block->getChildHtml('recurring_additional_info') ?>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "worldpay_subscription": {
                        "component": "Sapient_Worldpay/js/subscription",
                        "pm_elementId": "#change-payment-method",
                        "sp_elementId": "#change-shipping-address",
                        "sp_popelement": "#change_shipping_modal",
                        "pm_popelement": "#change_payment_modal",
                        "order_incrementId": "<?= /* @noEscape */ $escaper->escapeHtml(
                                __($block->getCurrentSubscriptionOrder()->getOriginalOrderIncrementId())
                            ); ?>",
                        "current_subscription_id": "<?= /* @noEscape */ $escaper->escapeHtml(
                                __($block->getCurrentSubscriptionOrder()->getId())
                            ); ?>"
                    }
                }
            }
        }
    }
</script>
