<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Multishipping\Block\Checkout\Success $block */
?>
<script>
require([
     'Magento_Customer/js/customer-data'
 ], function (customerData) {
     var sections = ['cart'];
     customerData.reload(sections, true);
 });
</script>
<form action="<?= $block->escapeUrl($block->getContinueUrl()); ?>" method="post">
    <div class="multicheckout success">   
        <p><?= $block->escapeHtml(__('An email has been sent to your email id with the payment link. 
        Please do the payment.')) ?></p>        
        <?php if ($orderIds = $block->getOrderIds()): ?>
            <h3><?= $block->escapeHtml(__('Successfully ordered'))?></h3>
            <div class="orders-succeed">
            <ul class="orders-list">
            <?php foreach ($orderIds as $orderId => $incrementId): ?>
                <li class="shipping-list">
                    <div class="order-id"><a href="<?= $block->escapeUrl($block->getViewOrderUrl($orderId)); ?>">
                        <?= $block->escapeHtml($incrementId); ?></a>
                    </div>
                <?php $shippingAddress = $block->getCheckoutData()->getOrderShippingAddress($orderId); ?>
                    <div class="shipping-item">
                        <?php if ($shippingAddress): ?>
                        <span class="shipping-label"><?= $block->escapeHtml(__('Ship to:')); ?></span>
                        <span class="shipping-address">
                            <?= $block->escapeHtml(
                                $block->getCheckoutData()->formatOrderShippingAddress($shippingAddress)
                            ); ?>
                        </span>
                        <?php else: ?>
                            <span class="shipping-address">
                                <?= $block->escapeHtml(__('No shipping required.')); ?>
                            </span>
                        <?php endif; ?>
                    </div>
                </li>
            <?php endforeach; ?>
            </ul>
            </div>
        <?php endif; ?>
        <?= $block->getChildHtml() ?>
        <div class="actions-toolbar" id="review-buttons-container">
            <div class="primary">
                <button type="submit"
                        class="action primary submit"><span><?= $block->escapeHtml(__('Continue Shopping')); ?></span>
                </button>
            </div>
        </div>
    </div>
</form>
