<?php
/**
 * Copyright © 2018 Worldpay, LLC. All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var $block \Sapient\Worldpay\Block\Recurring\Customer\Subscriptions\Edit
 */
?>
<form class="worldpay-subscription-edit" action="<?php echo $block->getSaveUrl() ?>" method="post" id="worldpay-subscription-edit" enctype="multipart/form-data" data-hasrequired="<?php echo __('* Required Fields') ?>">
    <fieldset class="fieldset subscription">
        <?php echo $block->getBlockHtml('formkey')?>
        <legend class="legend"><span><?php echo $block->getMyAccountLabels('AC25') ?></span></legend>
        <div class="field product-name">
            <label class="label" for="product_name"><span><?php echo $this->escapeHtml($block->getMyAccountLabels('AC26')) ?></span></label>
            <div class="control">
                <span><?= $this->escapeHtml(__($block->getSubscription()->getProductName())); ?></span>
            </div>
        </div>
        <?php if($block->getPlans()) : ?>
            <div class="field plan">
                <label class="label" for="plan"><span><?php echo $this->escapeHtml($block->getMyAccountLabels('AC27')) ?></span></label>
                <?php foreach ($block->getPlans() as $plan): ?>
                    <div class="field choice">
                        <?php if ($block->isPlanSelected($plan)): ?>
                        <input type="radio"
                               name="plan_id"
                               id="plan_id_<?php echo $plan->getId() ?>"
                               value="<?php echo $plan->getId() ?>"
                               checked />
                        <label class="label" for="plan_id_<?php echo $plan->getId() ?>">
                            <span><?php echo $block->getPlanTitle($plan); ?></span>
                        </label>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
                
            </div>
        <?php endif; ?>
    </fieldset>
    <fieldset class="fieldset billing">
       <legend class="legend"><span><?php echo $block->getMyAccountLabels('AC31') ?></span></legend>
        <div class="field firstname required">
            <label class="label" for="firstname"><span><?php echo $this->escapeHtml($block->getMyAccountLabels('AC32')) ?></span></label>
            <div class="control">
                <input type="text" name="firstname" data-validate="{required : true, maxlength : 25}" value="<?php echo $block->escapeHtml($block->getSubscription()->getBillingAddress()->getFirstname()) ?>" id="firstname" class="input-text" title="<?php echo $this->escapeHtml(__('First Name')) ?>"/>
            </div>
        </div>
        <div class="field lastname required">
            <label class="label" for="lastname"><span><?php echo $this->escapeHtml($block->getMyAccountLabels('AC33')) ?></span></label>
            <div class="control">
                <input type="text" name="lastname" data-validate="{required : true, maxlength : 25}" value="<?php echo $block->escapeHtml($block->getSubscription()->getBillingAddress()->getLastname()) ?>" id="lastname" class="input-text" title="<?php echo $this->escapeHtml(__('Last Name')) ?>"/>
            </div>
        </div>
        <div class="field street required">
            <label class="label" for="street"><span><?php echo $this->escapeHtml($block->getMyAccountLabels('AC34')) ?></span></label>
            <div class="control">
                <input type="text" name="street" data-validate="{required : true, maxlength : 35}" value="<?php echo $block->escapeHtml($block->getSubscription()->getBillingAddress()->getStreet()) ?>" id="street" class="input-text" title="<?php echo $this->escapeHtml(__('Address')) ?>"/>
            </div>
        </div>
        <div class="field city required">
            <label class="label" for="city"><span><?php echo $block->getMyAccountLabels('AC35') ?></span></label>
            <div class="control">
                <input type="text" name="city" data-validate="{required : true, maxlength : 35}" value="<?php echo $block->escapeHtml($block->getSubscription()->getBillingAddress()->getCity()) ?>" title="<?php echo __('City') ?>" class="input-text" id="city" title="<?php echo __('City') ?>"/>
            </div>
        </div>
        <div class="field region required">
            <label class="label" for="region_id"><span><?php echo __('State/Province') ?></span></label>
            <div class="control">
                <select id="region_id" name="region_id" title="<?php echo $block->getMyAccountLabels('AC38') ?>" class="validate-select">
                    <option value=""><?php echo __('Please select a region, state or province.') ?></option>
                </select>
                <input type="text" id="region" name="region" value="<?php echo $block->escapeHtml($block->getSubscription()->getBillingAddress()->getRegion()) ?>"  title="<?php echo __('State/Province') ?>" class="input-text required-entry"/>
            </div>
        </div>
        <div class="field zip required">
            <label class="label" for="zip"><span><?php echo $block->getMyAccountLabels('AC36') ?></span></label>
            <div class="control">
                <input type="text" name="postcode" data-validate="{required : true, maxlength : 20}" value="<?php echo $block->escapeHtml($block->getSubscription()->getBillingAddress()->getPostcode()) ?>" title="<?php echo __('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international"/>
            </div>
        </div>
        <div class="field country required">
            <label class="label" for="country"><span><?php echo $block->getMyAccountLabels('AC37') ?></span></label>
            <div class="control">
                <?php echo $this->getLayout()->createBlock('\Magento\Directory\Block\Data')->getCountryHtmlSelect($block->getSubscription()->getBillingAddress()->getCountryId()) ?>
            </div>
        </div>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button
                    type="submit"
                    class="action save primary"
                    data-action="save-subscription"
                    title="<?php echo $block->escapeHtml($block->getMyAccountLabels('AC28')); ?>"
            >
                <span><?php echo $block->escapeHtml($block->getMyAccountLabels('AC28')); ?></span>
            </button>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "#worldpay-subscription-edit": {
            "validation": {}
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#worldpay-subscription-edit",
                "regionJson": <?php echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php echo $block->getSubscription()->getBillingAddress()->getRegionId() ?>",
                "countriesWithOptionalZip": <?php echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
