<?php
/**
 * Copyright © 2020 Worldpay, LLC. All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $subscriptions = $block->getSubscriptions(); ?>
<?php if ($subscriptions && count($subscriptions)): ?>
    <div class="table-wrapper subscriptions-list">
        <table class="data table table-subscriptions-items" id="my-subscriptions-table">
            <caption class="table-caption"><?php echo $block->escapeHtml(__('Subscriptions')) ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col original-order-id"><?php echo $block->escapeHtml(__('Original Order #')) ?></th>
                <th scope="col" class="col original-order-date"><?php echo $block->escapeHtml(__('Original Order Date')) ?></th>
                <th scope="col" class="col product"><?php echo $block->escapeHtml(__('Product')) ?></th>
                <th scope="col" class="col interval-amount"><?php echo $block->escapeHtml(__('Amount')) ?></th>
                <th scope="col" class="col interval"><?php echo $block->escapeHtml(__('Interval')) ?></th>
                <th scope="col" class="col start-date"><?php echo $block->escapeHtml(__('Start Date')) ?></th>
                <th scope="col" class="col status"><?php echo $block->escapeHtml(__('Status')) ?></th>
                <th scope="col" class="col actions"><?php echo $block->escapeHtml(__('Actions')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($subscriptions as $subscription): ?>
                <tr>
                    <td data-th="<?php echo $block->escapeHtml(__('Original Order #')) ?>" class="col original-order-id"><?php /* @noEscape */
                        echo $block->getOrderIdLabel($subscription) ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Original Order Date')) ?>" class="col original-order-date"><?php /* @noEscape */
                        echo $block->formatDate($subscription->getCreatedAt()) ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Product')) ?>" class="col product"><?php echo $block->escapeHtml($subscription->getProductName()) ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Amount')) ?>" class="col interval-amount"><?php /* @noEscape */
                        echo $subscription->getFormattedIntervalAmount() ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Interval')) ?>" class="col interval"><?php echo $block->escapeHtml($block->getSubscriptionIntervalLabel($subscription)) ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Start Date')) ?>" class="col start-date"><?php /* @noEscape */
                        echo $block->formatDate($subscription->getStartDate(), \IntlDateFormatter::SHORT, false, date_default_timezone_get()) ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Status')) ?>" class="col status"><?php echo $block->escapeHtml($subscription->getStatusLabel()) ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <?php if($subscription->getStatus() == 'active') : ?>
                            <a href="<?php echo $block->getEditUrl($subscription); ?>" class="action edit"><span><?php echo __('Edit') ?></span></a>
                            <a href="javascript:void(0)" data-cancel-url="<?php echo $block->getCancelUrl($subscription); ?>" class="action delete"><span><?php echo __('Cancel') ?></span></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <script type="text/javascript">
            require([
                'jquery',
                'Magento_Ui/js/modal/confirm'
            ], function($, confirm) {

                $('.action.delete').on("click", function(event) {
                    confirm({
                        title: 'Cancel Subscription',
                        content: getMyAccountExceptions('MCAM12'),
                        actions: {
                            confirm: function() {
                                window.location.href = $(event.currentTarget).data('cancel-url');
                            }
                        }
                    });
                });
            });
            function getMyAccountExceptions (exceptioncode){
                var data=window.MyAccountExceptions;
                var gendata=JSON.parse(data);
                for (var key in gendata) {
                    if (gendata.hasOwnProperty(key)) {  
                        var cxData=gendata[key];
                    if(cxData['exception_code'].includes(exceptioncode)){
                        return cxData['exception_module_messages']?cxData['exception_module_messages']:cxData['exception_messages'];
                    }
                    }
                }
            }
        </script>
    </div>
    <?php if ($paginationHtml = $block->getPaginationHtml()): ?>
        <div class="susbcriptions-toolbar toolbar bottom"><?php /* @noEscape */
            echo $paginationHtml; ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty">
        <span><?php 
        $msg = $block->getMyAccountSpecificException('MCAM13');
        echo $block->escapeHtml(__($msg)); ?></span></div>
<?php endif ?>
