<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php /** @var $block \Sapient\Worldpay\Block\Paybylink */ ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <p>
            <?= $escaper->escapeHtml(
                __('Your order number is: %1.', sprintf(
                    '<a href="%s" class="order-number"><strong>%s</strong></a> has been created but not confirmed.',
                    $escaper->escapeUrl($block->getViewOrderUrl()),
                    $block->getOrderId()
                )),
                ['a', 'strong']
            ) ?>
        </p>
        <p><?= $escaper->escapeHtml(__('An email has been sent to your email id with the payment link.
        Please do the payment.')) ?></p>
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= $escaper->escapeUrl(
                $block->getContinueUrl()
            ) ?>">
                <span><?= $escaper->escapeHtml(__('Continue Shopping')) ?></span></a>
        </div>
    </div>
</div>
