<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<button type="button" id='checkout-now-bottom'
    title="<?= /* @noEscape */ __('Checkout Now') ?>"    
    data-mage-init='{"Sapient_Worldpay/js/proceed-to-checkout":{"checkoutNowUrl":"<?= /* @noEscape */
    $block->getCheckoutUrl() ?>"}}'
    class="action primary checkout<?= ($block->isDisabled()) ? ' disabled' : '' ?>"
    <?php if ($block->isDisabled()):?>disabled="disabled"<?php endif; ?>>
    <span><?= /* @noEscape */ __('Checkout Now') ?></span>
</button>
<script type="text/javascript">
 if(window.ChromepayEnabled == 1 && window.ChromePaymentMode == 'direct' 
         && window.SubscriptionStatus == "" && window.ChromepayAvailable == '1') {
    var buttonObj = document.getElementById("checkout-now-bottom");
    buttonObj.value = window.ChromepayButtonName;
    buttonObj.innerHTML = window.ChromepayButtonName;
 }else{
     document.getElementById('checkout-now-bottom').style.visibility='hidden';
 }
</script>
