<?php
// This template is loaded on the multi-shipping checkout page while selction Credit Card
?>
<script>
    require([
        'uiLayout',
        'jquery'
    ], function (layout, $) {
        $(function () {
            var paymentMethodData = {
                method: 'worldpay_cc'
            };
            layout([
                {
                    component: 'Sapient_Worldpay/js/view/payment/multishipping/cc-method',
                    name: 'payment_method_worldpay_cc',
                    method: paymentMethodData.method,
                    item: paymentMethodData
                }
            ]);
            $('body').trigger('contentUpdated');
        })
    })
</script>
<fieldset id="payment_form_worldpay_cc" 
class="worldpay_cc worldpay_cc_multishipping standard-form worldpay-ms fieldset items" 
style="display: none;">

  <div data-bind="scope: 'payment_method_worldpay_cc'">
    <!-- ko template: getTemplate() -->
    <!-- /ko -->

  </div>

</fieldset>