<?php
// This template is loaded on the multi-shipping checkout page while selecting Wallets
?>
<script>
    require([
        'uiLayout',
        'jquery'
    ], function (layout, $) {
        $(function () {
            var paymentMethodData = {
                method: 'worldpay_wallets'
            };
            layout([
                {
                    component: 'Sapient_Worldpay/js/view/payment/multishipping/wallets-method',
                    name: 'payment_method_worldpay_wallets',
                    method: paymentMethodData.method,
                    item: paymentMethodData
                }
            ]);
            $('body').trigger('contentUpdated');
        })
    })
</script>
<fieldset id="payment_form_worldpay_wallets"
          class="worldpay_wallets worldpay_wallets_multishipping worldpay-ms standard-form fieldset items"
          style="display: none;">

  <div data-bind="scope: 'payment_method_worldpay_wallets'">
    <!-- ko template: getTemplate() -->
    <!-- /ko -->

  </div>

</fieldset>
