<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Sapient\Worldpay\Block\ApplePay\Button $block */
?>
<?php if ($block->isApplePayEnableonPdp()) {; ?>
<div id="wp-apple-pay-btn">
<apple-pay-button buttonstyle="<?= $block->isApplePayButtonColor() ?>" id = "apple-pay-buy" data-bind="visible: isAppleDevice,click: addtoCartandInitApplePay" type="<?= $block->isApplePayButtonType() ?>" locale="<?= $block->isApplePayButtonLocale() ?>">
</apple-pay-button></div>
<style>
:root {
    --apple-pay-button-height: 40px;
}
apple-pay-button{
    display:inline-block;
    width:var(--apple-pay-button-width, 242px);
    min-width : 50px;
    min-height : 50px;
    margin-bottom : 5px;
}
@media only screen and (max-width: 768px) {
    #apple-pay-buy {width: 100%;}
}
</style>
<?php } ?>
