<?php
$isworldpayment=$block->isWorldpayPayment();
if ($isworldpayment):
    $payment = $block->getWorldPaymentsDetails();
    ?>

<table class="fieldset">
            <tr>
                <td class="label"><label>Worldpay Order Id</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getWorldpayOrderId() ?></strong></td>
            </tr>
        <tr>
                <td class="label"><label>Payment Status</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getPaymentStatus() ?></strong></td>
            </tr>
               <?php if ($payment->getRefusalCode()): ?>
                <tr>
                    <td class="label">
                        <label><?= /* @noEscape */ $block->escapeHtml(__('Refusal Description')); ?></label>
                    </td>
                    <td class="value">
                        <strong><?= /* @noEscape */ $payment->getRefusalDescription() ?>
                            (<?= /* @noEscape */ $payment->getRefusalCode() ?>)
                        </strong>
                    </td>
                </tr>
            <?php endif; ?>
            <tr>
                <td class="label"><label>Payment Model</label></td>
                <td class="value"><strong><?= /* @noEscape */ ucwords($payment->getPaymentModel()) ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>Multishipping</label></td>
                <td class="value">
                    <strong><?= /* @noEscape */ ucwords($payment->getIsMultishippingOrder()? "YES" : "NO") ?>
                    </strong>
                </td>
            </tr>
            <?php if ($payment->getIsMultishippingOrder()): ?>
            <tr>
                <td class="label"><label>Multishipping Order Id</label></td>
                <td class="value">
                    <strong><?= /* @noEscape */ $payment->getWorldpayOrderId() ?>
                    </strong>
                </td>
            </tr>
            <tr>
                <td class="label"><label>Multishipping Orders</label></td>
                <td class="value">
                    <strong><?= /* @noEscape */ $block->getMultishippingOrderIds() ?>
                    </strong>
                </td>
            </tr>
            <?php endif; ?>
            <?php if ($payment->getPaymentModel() == 'direct'): ?>
                <tr>
                    <td class="label"><label>Client side encryption</label></td>
                    <td class="value">
                        <strong><?= /* @noEscape */ ucwords($payment->getClientSideEncryption()? "YES" : "NO") ?>
                        </strong>
                    </td>
                </tr>
            <?php endif; ?>
            <tr>
                <td class="label"><label>Payment Method</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getPaymentType() ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>Card Number</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getCardNumber() ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>AVS Result</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getAvsResult() ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>CVC Result</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getCvcResult() ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>Basic Risk Score</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getRiskScore() ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>Advanced Risk Provider</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getRiskProvider() ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>Advanced Risk Score</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getRiskProviderScore() ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>Advanced Risk Threshold</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getRiskProviderThreshold() ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>Advanced Risk Final Score</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getRiskProviderFinal() ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>Advanced Risk Id</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getRiskProviderId() ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>AAV Address Result Code</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getAavAddressResultCode() ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>AAV Postcode Result Code</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getAvvPostcodeResultCode() ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>AAV Telephone Result Code</label></td>
                <td class="value">
                    <strong><?= /* @noEscape */ $payment->getAavCardholderNameResultCode() ?>
                    </strong>
                </td>
            </tr>
            <tr>
                <td class="label"><label>AAV Email Result Code </label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getAavEmailResultCode() ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>AAV Cardholder Name Result Code</label></td>
                <td class="value">
                    <strong><?= /* @noEscape */ $payment->getAavCardholderNameResultCode() ?>
                    </strong>
                </td>
            </tr>
            <tr>
                <td class="label"><label>Interaction Type</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getInteractionType() ?></strong></td>
            </tr>
            <tr>
                <td style="padding-top: .5em;">
                    <span style="font-weight:600;font-size:1.7rem;">Issuer Insights</span>
                </td>
            </tr>
            <tr>
                <td class="label"><label>Source Type</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getSourceType() ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>Available Balance</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getAvailableBalance() ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>Reloadable</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getReloadable() ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>Prepaid Card Type</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getPrepaidCardType() ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>Affluence</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getAffluence() ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>Issuer Country</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getIssuerCountry() ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>Card Product Type</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getCardProductType() ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>Virtual Account Number</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getVirtualAccountNumber() ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>Account Range Id</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getAccountRangeId() ?></strong></td>
            </tr>
            
            <tr>
                <td style="padding-top: .5em;">
                    <span style="font-weight:600;font-size:1.7rem;">Fraudsight Data</span>
                </td>
            </tr>
            <tr>
                <td class="label"><label>Fraudsight Message</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getFraudsightMessage() ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>Fraudsight Score</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getFraudsightScore() ?></strong></td>
            </tr>
            <tr style="padding-top: .2em;">
                <td class="label"><label>Fraudsight ReasonCodes</label></td>
                <td class="value">
                        <div style="width: 280px; word-wrap: break-word">
                            <b><?= /* @noEscape */ $payment->getFraudsightReasoncode() ?></b>
                        </div>
                    </td>
            </tr> 
            <tr>
                <td style="padding-top: .5em;" colspan="2">
                    <span style="font-weight:600;font-size:1.7rem;">Worldpay Merchant Information</span>
                </td>
            </tr>
            <tr>
                <td class="label"><label>Merchant Code</label></td>
                <td class="value"><strong><?= /* @noEscape */ $payment->getMerchantId() ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label>XML Username</label></td>
                <td class="value">
                    <strong>
                        <?= /* @noEscape */ $block->getXmluserName(
                            $payment->getPaymentType(),
                            $payment->getIsMultishippingOrder()
                        ) ?>
                    </strong>
                </td>
            </tr>            
            </table>

<?php endif; ?>

